[project]
name = "rag-prototype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]",
    "ollama",
    "pymilvus[model,milvus_lite]>=2.7.0",
    "Flax",
    "websockets>=15.0.1",
    "google-genai>=1.64.0",
    "fastmcp>=3.3.1",
    "pytest>=9.0.3",
    "pydantic",
    "torch",
    "transformers",
    "sentence-transformers",
    "httpx>=0.28.1",
    "pytest-asyncio>=1.4.0",
    "google-adk>=2.0.0",
    "google-adk[eval]",
    "pydantic>=2.12.4",
    "requests>=2.32.5",
    "pyrefly>=0.60.0",
    "ruff>=0.15.18",
    "scipy-stubs~=1.16.3",
    "matplotlib>=3.10.9",
    "numpy>=2.3.4",
    "scipy>=1.16.3",
]

[tool.uv.sources]
google-adk = { git = "https://github.com/he-yufeng/adk-python", branch = "fix/workflow-empty-state" }

# Suggested by fastmcp docs
[tool.pytest.ini_options]
asyncio_mode = "auto"
