[project]
name = "rag-prototype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]",
    "ollama",
    "pymilvus>=2.6.2",
    "pymilvus-model",
    "pymilvus[milvus_lite]",
    "Flax",
    "websockets>=15.0.1",
    "google-generativeai>=0.8.6",
    "google-genai>=1.64.0",
    "fastmcp>=3.3.1",
    "adk>=0.0.5",
    "pytest>=9.0.3",
    "httpx>=0.28.1",
    "pytest-asyncio>=1.4.0",
]

# Suggested by fastmcp docs
[tool.pytest.ini_options]
asyncio_mode = "auto"
