on:
  push:
    branches:
      - dev
# Template using https://docs.astral.sh/uv/guides/integration/github/#installation
jobs:
  test_backend:
    name: Test Backend
    runs-on: ubuntu-latest
    environment: actions-environment

    steps:
      - uses: actions/checkout@v6

      - name: Install Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Start Ollama
        run: ollama serve

      - name: Wait for Ollama to be Ready
        run: |
          until curl -s http://127.0.0.1:11434 > /deb/null; do
            sleep 1
          done

      - name: Pull configured model
        run: ollama pull ${{ vars.AI_MODEL }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install Project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          AI_MODEL: ${{ vars.AI_MODEL }}
          DB_URL: ${{ vars.DB_URL }}
          POI_JSON_PATH: ${{ vars.POI_JSON_PATH }}
        run: uv run pytest ./app/tests/tests.py
